param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("install", "uninstall", "build")]
    [string]$Action
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$MuxerDir = Join-Path $HOME ".dotnet-muxer"
$BeginMarker = "# >>> dotnet-muxer (generated by https://github.com/user/dotnet-muxer-rs) >>>"
$EndMarker = "# <<< dotnet-muxer <<<"

function Build-DotnetMuxer {
    cargo clean --manifest-path (Join-Path $Root "Cargo.toml")
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    cargo build --release --manifest-path (Join-Path $Root "Cargo.toml")
    exit $LASTEXITCODE
}

function Install-DotnetMuxer {
    Write-Host "Building dotnet-muxer..."
    cargo build --release --manifest-path (Join-Path $Root "Cargo.toml")
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host "Installing to $MuxerDir..."
    New-Item -ItemType Directory -Force -Path $MuxerDir | Out-Null
    Copy-Item (Join-Path $Root "target/release/dotnet.exe") (Join-Path $MuxerDir "dotnet.exe") -Force

    $ProfilePath = $PROFILE.CurrentUserAllHosts
    $ProfileDir = Split-Path $ProfilePath -Parent
    if (-not (Test-Path $ProfileDir)) {
        New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
    }

    $Block = @"

$BeginMarker
`$__dotnet_muxer_prev_code = if (Test-Path Function:\code) { Get-Item Function:\code } else { `$null }
function code {
    if (`$args.Count -ge 1 -and (Test-Path `$args[0] -PathType Container) -and
        (Test-Path (Join-Path `$args[0] ".dotnet\dotnet.exe"))) {
        `$repoRoot = (Resolve-Path `$args[0]).Path
        `$env:DOTNET_MUXER_TARGET = `$repoRoot
        `$env:PATH = "`$HOME\.dotnet-muxer;`$env:PATH"
        `$env:DOTNET_MULTILEVEL_LOOKUP = "0"
    }
    if (`$__dotnet_muxer_prev_code) {
        & `$__dotnet_muxer_prev_code @args
    } else {
        & (Get-Command code.cmd -CommandType Application | Select-Object -First 1) @args
    }
}
$EndMarker
"@

    if (Test-Path $ProfilePath) {
        $content = Get-Content $ProfilePath -Raw
        if ($content -match "dotnet-muxer") {
            $content = $content -replace "(?s)\r?\n?$([regex]::Escape($BeginMarker)).*?$([regex]::Escape($EndMarker))", ""
            Set-Content $ProfilePath -Value $content -NoNewline
            Write-Host "Replaced existing dotnet-muxer block in $ProfilePath"
        } else {
            Write-Host "Adding dotnet-muxer block to $ProfilePath"
        }
    } else {
        Write-Host "Creating $ProfilePath"
    }

    Add-Content $ProfilePath -Value $Block

    Write-Host ""
    Write-Host "Done. When you run 'code /path/to/repo' and the repo has .dotnet/dotnet.exe,"
    Write-Host "VSCode will automatically use the muxer with the correct target."
    Write-Host ""
    Write-Host "Optional: `$env:DOTNET_MUXER_VERBOSE = '1'  (logs to $MuxerDir\log.log)"
    exit 0
}

function Uninstall-DotnetMuxer {
    Remove-Item -ErrorAction SilentlyContinue -Force @(
            (Join-Path $MuxerDir "dotnet.exe"),
            (Join-Path $MuxerDir "dotnet"),
            (Join-Path $MuxerDir "log.log")
        )

    $ProfilePath = $PROFILE.CurrentUserAllHosts
    if (Test-Path $ProfilePath) {
        $content = Get-Content $ProfilePath -Raw
        $content = $content -replace "(?s)\r?\n?$([regex]::Escape($BeginMarker)).*?$([regex]::Escape($EndMarker))", ""
        Set-Content $ProfilePath -Value $content -NoNewline
    }

    Write-Host "Uninstalled dotnet-muxer from $MuxerDir and removed shell hooks from PowerShell profile"
    exit 0
}

switch ($Action) {
    "install" {
        Install-DotnetMuxer
    }
    "uninstall" {
        Uninstall-DotnetMuxer
    }
    "build" {
        Build-DotnetMuxer
    }
}
