#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
MUXER_DIR="$HOME/.dotnet-muxer"
BEGIN_MARKER="# >>> dotnet-muxer (generated by https://github.com/user/dotnet-muxer-rs) >>>"
END_MARKER="# <<< dotnet-muxer <<<"

usage() {
    echo "Usage: ./run.sh <install|uninstall|build|bench|bench-forward>"
}

build() {
    cargo clean --manifest-path "$ROOT_DIR/Cargo.toml"
    cargo build --release --manifest-path "$ROOT_DIR/Cargo.toml"
}

bench() {
    local rid runs python_bin
    runs="${BENCH_RUNS:-200}"

    if [[ "$(uname -s)" == "Darwin" ]]; then
        rid="osx-arm64"
    elif [[ "$(uname -s)" == "Linux" ]]; then
        rid="linux-x64"
    else
        echo "bench is currently supported on macOS/Linux only in run.sh"
        exit 1
    fi

    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        echo "python3 (or python) is required for bench"
        exit 1
    fi

    cargo build --release --manifest-path "$ROOT_DIR/Cargo.toml"
    dotnet publish "$ROOT_DIR/dotnet/DotnetMuxer.csproj" -c Release -r "$rid"

    "$python_bin" - <<PY
import subprocess, time, statistics
from pathlib import Path

root = Path(r"$ROOT_DIR")
rust = root / "target/release/dotnet"
dotnet = root / "dotnet/bin/Release/net10.0/$rid/publish/DotnetMuxer"

if not rust.exists():
    raise SystemExit(f"Missing Rust binary: {rust}")
if not dotnet.exists():
    raise SystemExit(f"Missing .NET AOT binary: {dotnet}")

print("== Size ==")
print(f"Rust:      {rust.stat().st_size:,} bytes")
print(f".NET AOT:  {dotnet.stat().st_size:,} bytes")

cases = [("rust", str(rust)), ("dotnet-aot", str(dotnet))]
N = int(r"$runs")
warmup = min(20, max(5, N // 10))

print("\\n== Startup benchmark (ms) ==")
for name, exe in cases:
    for _ in range(warmup):
        subprocess.run([exe], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    times = []
    for _ in range(N):
        t0 = time.perf_counter()
        subprocess.run([exe], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        times.append((time.perf_counter() - t0) * 1000)

    p95 = statistics.quantiles(times, n=20)[18] if len(times) >= 20 else max(times)
    print(f"{name}: n={N} avg={statistics.mean(times):.3f} p50={statistics.median(times):.3f} p95={p95:.3f} min={min(times):.3f} max={max(times):.3f}")
PY
}

bench_forward() {
    local rid runs python_bin
    runs="${BENCH_RUNS:-200}"

    if [[ "$(uname -s)" == "Darwin" ]]; then
        rid="osx-arm64"
    elif [[ "$(uname -s)" == "Linux" ]]; then
        rid="linux-x64"
    else
        echo "bench-forward is currently supported on macOS/Linux only in run.sh"
        exit 1
    fi

    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        echo "python3 (or python) is required for bench-forward"
        exit 1
    fi

    cargo build --release --manifest-path "$ROOT_DIR/Cargo.toml"
    dotnet publish "$ROOT_DIR/dotnet/DotnetMuxer.csproj" -c Release -r "$rid"

    "$python_bin" - <<PY
import os, stat, subprocess, tempfile, time, statistics
from pathlib import Path

root = Path(r"$ROOT_DIR")
rust = root / "target/release/dotnet"
dotnet = root / "dotnet/bin/Release/net10.0/$rid/publish/DotnetMuxer"

if not rust.exists():
    raise SystemExit(f"Missing Rust binary: {rust}")
if not dotnet.exists():
    raise SystemExit(f"Missing .NET AOT binary: {dotnet}")

N = int(r"$runs")
warmup = min(20, max(5, N // 10))

with tempfile.TemporaryDirectory(prefix="dotnet-muxer-bench-") as tmp:
    repo = Path(tmp)
    dotnet_dir = repo / ".dotnet"
    dotnet_dir.mkdir(parents=True, exist_ok=True)

    fake = dotnet_dir / "dotnet"
    fake.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    fake.chmod(fake.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    env = os.environ.copy()
    env["DOTNET_MUXER_TARGET"] = str(fake)
    env.pop("DOTNET_MUXER_VERBOSE", None)

    cases = [("rust-forward", str(rust)), ("dotnet-aot-forward", str(dotnet))]

    print("== Forward benchmark (ms) ==")
    print(f"DOTNET_MUXER_TARGET={fake}")

    for name, exe in cases:
        for _ in range(warmup):
            subprocess.run([exe], env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        times = []
        for _ in range(N):
            t0 = time.perf_counter()
            subprocess.run([exe], env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            times.append((time.perf_counter() - t0) * 1000)

        p95 = statistics.quantiles(times, n=20)[18] if len(times) >= 20 else max(times)
        print(f"{name}: n={N} avg={statistics.mean(times):.3f} p50={statistics.median(times):.3f} p95={p95:.3f} min={min(times):.3f} max={max(times):.3f}")
PY
}

install() {
    echo "Building dotnet-muxer..."
    cargo build --release --manifest-path "$ROOT_DIR/Cargo.toml"

    echo "Installing to $MUXER_DIR..."
    mkdir -p "$MUXER_DIR"
    cp "$ROOT_DIR/target/release/dotnet" "$MUXER_DIR/dotnet"
    chmod +x "$MUXER_DIR/dotnet"

    local shell_name rc
    shell_name=$(basename "${SHELL:-/bin/bash}")
    case "$shell_name" in
        zsh) rc="$HOME/.zshrc" ;;
        *) rc="$HOME/.bashrc" ;;
    esac

    if grep -q "dotnet-muxer" "$rc" 2>/dev/null; then
        sed -i.bak '/# >>> dotnet-muxer/,/# <<< dotnet-muxer/d' "$rc" && rm -f "$rc.bak"
        echo "Replaced existing dotnet-muxer block in $rc"
    else
        echo "Adding dotnet-muxer block to $rc"
    fi

    cat >> "$rc" << DOTNET_MUXER_EOF

$BEGIN_MARKER
if declare -f code > /dev/null 2>&1; then
    eval "\\\$(declare -f code | sed '1s/code/__dotnet_muxer_prev_code/')"
fi
code() {
    if [ -n "\$1" ] && [ -d "\$1" ] && [ -f "\$1/.dotnet/dotnet" ]; then
        export DOTNET_MUXER_TARGET="\$(cd "\$1" && pwd)/.dotnet/dotnet"
        export PATH="\$HOME/.dotnet-muxer:\$PATH"
        export DOTNET_MULTILEVEL_LOOKUP=0
        if ! command -v mono >/dev/null 2>&1; then
            export BuildTargetFramework=net11.0
        fi
    fi
    if declare -f __dotnet_muxer_prev_code > /dev/null 2>&1; then
        __dotnet_muxer_prev_code "\$@"
    else
        command code "\$@"
    fi
}
$END_MARKER
DOTNET_MUXER_EOF

    echo ""
    echo "Done. When you run 'code /path/to/repo' and the repo has .dotnet/dotnet,"
    echo "VSCode will automatically use the muxer with the correct target."
    echo ""
    echo "Optional: export DOTNET_MUXER_VERBOSE=1  (logs to $MUXER_DIR/log.log)"
}

uninstall() {
    rm -f "$MUXER_DIR/dotnet" "$MUXER_DIR/dotnet.exe" "$MUXER_DIR/log.log"

    for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
        if [ -f "$rc" ]; then
            sed -i.bak '/# >>> dotnet-muxer/,/# <<< dotnet-muxer/d' "$rc" && rm -f "$rc.bak"
        fi
    done

    echo "Uninstalled dotnet-muxer from $MUXER_DIR and removed shell hooks from .zshrc/.bashrc"
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi

case "$1" in
    install)
        install
        ;;
    uninstall)
        uninstall
        ;;
    build)
        build
        ;;
    bench)
        bench
        ;;
    bench-forward)
        bench_forward
        ;;
    *)
        usage
        exit 1
        ;;
esac
