#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
MUXER_DIR="$HOME/.dotnet-muxer"
BEGIN_MARKER="# >>> dotnet-muxer (generated by https://github.com/user/dotnet-muxer) >>>"
END_MARKER="# <<< dotnet-muxer <<<"

detect_rid() {
    case "$(uname -s)" in
        Darwin)
            echo "osx-arm64"
            ;;
        Linux)
            echo "linux-x64"
            ;;
        *)
            echo "Unsupported OS for run.sh"
            exit 1
            ;;
    esac
}

detect_tfm() {
    local latest_major
    latest_major="$(dotnet --list-sdks 2>/dev/null | awk -F. '{ if ($1 ~ /^[0-9]+$/) print $1 }' | sort -n | tail -1)"

    if [ -z "$latest_major" ]; then
        echo "Could not determine installed .NET SDK version from 'dotnet --list-sdks'"
        exit 1
    fi

    echo "net${latest_major}.0"
}

usage() {
    echo "Usage: ./run.sh <install|uninstall|build>"
}

build() {
    local rid tfm
    rid="$(detect_rid)"
    tfm="$(detect_tfm)"
    dotnet publish "$ROOT_DIR/src/DotnetMuxer/DotnetMuxer.csproj" -c Release -r "$rid" -p:BuildTargetFramework="$tfm"
}

install() {
    local rid tfm binary
    rid="$(detect_rid)"
    tfm="$(detect_tfm)"

    echo "Building dotnet-muxer..."
    dotnet publish "$ROOT_DIR/src/DotnetMuxer/DotnetMuxer.csproj" -c Release -r "$rid" -p:BuildTargetFramework="$tfm"

    binary="$ROOT_DIR/src/DotnetMuxer/bin/Release/$tfm/$rid/publish/DotnetMuxer"

    echo "Installing to $MUXER_DIR..."
    mkdir -p "$MUXER_DIR"
    cp "$binary" "$MUXER_DIR/dotnet"
    chmod +x "$MUXER_DIR/dotnet"

    local shell_name rc
    shell_name=$(basename "${SHELL:-/bin/bash}")
    case "$shell_name" in
        zsh) rc="$HOME/.zshrc" ;;
        *) rc="$HOME/.bashrc" ;;
    esac

    if grep -q "dotnet-muxer" "$rc" 2>/dev/null; then
        sed -i.bak '/# >>> dotnet-muxer/,/# <<< dotnet-muxer/d' "$rc" && rm -f "$rc.bak"
        echo "Replaced existing dotnet-muxer block in $rc"
    else
        echo "Adding dotnet-muxer block to $rc"
    fi

    cat >> "$rc" << DOTNET_MUXER_EOF

$BEGIN_MARKER
if declare -f code > /dev/null 2>&1; then
    eval "\\\$(declare -f code | sed '1s/code/__dotnet_muxer_prev_code/')"
fi
code() {
    if [ -n "\$1" ] && [ -d "\$1" ] && [ -f "\$1/.dotnet/dotnet" ]; then
        export DOTNET_MUXER_TARGET="\$(cd "\$1" && pwd)/.dotnet/dotnet"
        export PATH="\$HOME/.dotnet-muxer:\$PATH"
        export DOTNET_MULTILEVEL_LOOKUP=0
        if ! command -v mono >/dev/null 2>&1; then
            export BuildTargetFramework=net11.0
        fi
    fi
    if declare -f __dotnet_muxer_prev_code > /dev/null 2>&1; then
        __dotnet_muxer_prev_code "\$@"
    else
        command code "\$@"
    fi
}
$END_MARKER
DOTNET_MUXER_EOF

    echo ""
    echo "Done. When you run 'code /path/to/repo' and the repo has .dotnet/dotnet,"
    echo "VSCode will automatically use the muxer with the correct target."
    echo ""
    echo "Optional: export DOTNET_MUXER_VERBOSE=1  (logs to $MUXER_DIR/log.log)"
}

uninstall() {
    rm -f "$MUXER_DIR/dotnet" "$MUXER_DIR/dotnet.exe" "$MUXER_DIR/log.log"

    for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
        if [ -f "$rc" ]; then
            sed -i.bak '/# >>> dotnet-muxer/,/# <<< dotnet-muxer/d' "$rc" && rm -f "$rc.bak"
        fi
    done

    echo "Uninstalled dotnet-muxer from $MUXER_DIR and removed shell hooks from .zshrc/.bashrc"
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi

case "$1" in
    install)
        install
        ;;
    uninstall)
        uninstall
        ;;
    build)
        build
        ;;
    *)
        usage
        exit 1
        ;;
esac
