#!/bin/bash
set -e

MUXER_DIR="$HOME/.dotnet-muxer"
BEGIN_MARKER="# >>> dotnet-muxer (generated by https://github.com/user/dotnet-muxer-rs) >>>"
END_MARKER="# <<< dotnet-muxer <<<"

echo "Building dotnet-muxer..."
cargo build --release --manifest-path app/Cargo.toml

echo "Installing to $MUXER_DIR..."
mkdir -p "$MUXER_DIR"
cp app/target/release/dotnet "$MUXER_DIR/dotnet"
chmod +x "$MUXER_DIR/dotnet"

# Determine shell profile
SHELL_NAME=$(basename "${SHELL:-/bin/bash}")
case "$SHELL_NAME" in
    zsh)  RC="$HOME/.zshrc" ;;
    *)    RC="$HOME/.bashrc" ;;
esac

# Remove old block if present, then add fresh version
if grep -q "dotnet-muxer" "$RC" 2>/dev/null; then
    sed -i.bak '/# >>> dotnet-muxer/,/# <<< dotnet-muxer/d' "$RC" && rm -f "$RC.bak"
    echo "Replaced existing dotnet-muxer block in $RC"
else
    echo "Adding dotnet-muxer block to $RC"
fi

cat >> "$RC" << DOTNET_MUXER_EOF

$BEGIN_MARKER
if declare -f code > /dev/null 2>&1; then
    eval "\\\$(declare -f code | sed '1s/code/__dotnet_muxer_prev_code/')"
fi
code() {
    if [ -n "\$1" ] && [ -d "\$1" ] && [ -f "\$1/.dotnet/dotnet" ]; then
        export DOTNET_MUXER_TARGET="\$(cd "\$1" && pwd)"
        export PATH="\$HOME/.dotnet-muxer:\$PATH"
        export DOTNET_MULTILEVEL_LOOKUP=0
        if ! command -v mono >/dev/null 2>&1; then
            export BuildTargetFramework=net11.0
        fi
    fi
    if declare -f __dotnet_muxer_prev_code > /dev/null 2>&1; then
        __dotnet_muxer_prev_code "\$@"
    else
        command code "\$@"
    fi
}
$END_MARKER
DOTNET_MUXER_EOF

echo ""
echo "Done. When you run 'code /path/to/repo' and the repo has .dotnet/dotnet,"
echo "VSCode will automatically use the muxer with the correct target."
echo ""
echo "Optional: export DOTNET_MUXER_VERBOSE=1  (logs to $MUXER_DIR/log.log)"
