$ErrorActionPreference = "Stop"

$MuxerDir = Join-Path $HOME ".dotnet-muxer"
$BeginMarker = "# >>> dotnet-muxer (generated by https://github.com/user/dotnet-muxer-rs) >>>"
$EndMarker = "# <<< dotnet-muxer <<<"

Remove-Item -ErrorAction SilentlyContinue -Force \
    (Join-Path $MuxerDir "dotnet.exe"), \
    (Join-Path $MuxerDir "dotnet"), \
    (Join-Path $MuxerDir "log.log")

$ProfilePath = $PROFILE.CurrentUserAllHosts
if (Test-Path $ProfilePath) {
    $content = Get-Content $ProfilePath -Raw
    $content = $content -replace "(?s)\r?\n?$([regex]::Escape($BeginMarker)).*?$([regex]::Escape($EndMarker))", ""
    Set-Content $ProfilePath -Value $content -NoNewline
}

Write-Host "Uninstalled dotnet-muxer from $MuxerDir and removed shell hooks from PowerShell profile"
